name: Terraform Azure Example

on:
  push:
    branches: [ "dev" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev
        uses: actions/checkout@v4

      - name: Setup Terraform Dev
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init Dev
        run: terraform init
        working-directory: env/dev
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}


      # - name: Select/Create Workspace
      #   run: |
      #     terraform workspace list | grep -q '^dev$' || terraform workspace new dev
      #     terraform workspace select dev
      #   env:
      #     TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      #     TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      #     TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform Plan Dev
        run: terraform plan -out=dev-tfplan -var-file=dev.tfvars
        working-directory: env/dev
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Upload tfplan Dev
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: env/dev/dev-tfplan